apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: aura-vault
  labels:
    app: frontend
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: frontend
  unhealthyPodEvictionPolicy: AlwaysAllow
