export type Locale = "en" | "es" | "fr";

export interface FAQItem {
  id: string;
  category: string;
  q: string;
  a: string;
}

export interface FAQCategory {
  id: string;
  label: string;
}

export const categories: Record<Locale, FAQCategory[]> = {
  en: [
    { id: "getting-started", label: "Getting Started" },
    { id: "deposits", label: "Deposits" },
    { id: "withdrawals", label: "Withdrawals" },
    { id: "yield", label: "Yield & Harvest" },
    { id: "shares", label: "Shares & Pricing" },
    { id: "security", label: "Security" },
    { id: "technical", label: "Technical" },
    { id: "fees", label: "Fees & Costs" },
  ],
  es: [
    { id: "getting-started", label: "Primeros pasos" },
    { id: "deposits", label: "Depósitos" },
    { id: "withdrawals", label: "Retiros" },
    { id: "yield", label: "Rendimiento y cosecha" },
    { id: "shares", label: "Acciones y precios" },
    { id: "security", label: "Seguridad" },
    { id: "technical", label: "Técnico" },
    { id: "fees", label: "Tarifas y costos" },
  ],
  fr: [
    { id: "getting-started", label: "Démarrage" },
    { id: "deposits", label: "Dépôts" },
    { id: "withdrawals", label: "Retraits" },
    { id: "yield", label: "Rendement et récolte" },
    { id: "shares", label: "Parts et prix" },
    { id: "security", label: "Sécurité" },
    { id: "technical", label: "Technique" },
    { id: "fees", label: "Frais et coûts" },
  ],
};

const en: FAQItem[] = [
  // Getting Started
  {
    id: "gs-1",
    category: "getting-started",
    q: "What is Aura Vault Protocol?",
    a: "Aura Vault Protocol is a share-based yield vault built on Soroban for the Stellar ecosystem. It aggregates deposits of a single SEP-41-compatible token, issues proportional vault shares, and auto-compounds yield through permissionless keeper harvests.",
  },
  {
    id: "gs-2",
    category: "getting-started",
    q: "What do I need to use Aura Vault?",
    a: "You need a Stellar-compatible wallet, some XLM for transaction fees, and the underlying token accepted by the vault you want to deposit into.",
  },
  {
    id: "gs-3",
    category: "getting-started",
    q: "Which networks does Aura support?",
    a: "Aura Vault is deployed on Stellar Testnet for testing and Stellar Mainnet for production. Always verify the contract ID before interacting.",
  },
  {
    id: "gs-4",
    category: "getting-started",
    q: "Is Aura Vault non-custodial?",
    a: "Yes. Your funds are held entirely by the on-chain smart contract. No team member or admin can withdraw your tokens — only you can redeem your shares.",
  },
  {
    id: "gs-5",
    category: "getting-started",
    q: "How do I connect my wallet?",
    a: "Click 'Connect Wallet' on the app header and approve the connection in your Stellar wallet extension (e.g., Freighter).",
  },
  {
    id: "gs-6",
    category: "getting-started",
    q: "What is a vault share?",
    a: "A vault share represents your proportional ownership of the total assets in the vault. As yield is harvested, the value of each share increases — you don't receive more shares, you receive more underlying tokens per share when you withdraw.",
  },
  {
    id: "gs-7",
    category: "getting-started",
    q: "Is there a minimum deposit amount?",
    a: "There is no protocol-enforced minimum beyond requiring a non-zero amount. However, very small deposits may round to zero shares due to integer arithmetic, which the contract rejects with a ZeroAmount error.",
  },
  // Deposits
  {
    id: "dep-1",
    category: "deposits",
    q: "How do I deposit into the vault?",
    a: "Navigate to the Deposit tab, enter the amount of underlying tokens you want to deposit, and confirm the transaction in your wallet. Shares are minted and credited to your address instantly.",
  },
  {
    id: "dep-2",
    category: "deposits",
    q: "How are my shares calculated on deposit?",
    a: "The first depositor receives shares 1:1 with their deposit. Subsequent depositors receive floor(amount × total_shares / total_assets) shares, ensuring fair proportional ownership.",
  },
  {
    id: "dep-3",
    category: "deposits",
    q: "Can I deposit multiple times?",
    a: "Yes. Each deposit mints additional shares at the current exchange rate. Your total share balance accumulates across all deposits.",
  },
  {
    id: "dep-4",
    category: "deposits",
    q: "What token does the vault accept?",
    a: "Each vault accepts exactly one SEP-41-compatible underlying token, set at initialization. Check the vault's detail page to confirm the accepted token before depositing.",
  },
  {
    id: "dep-5",
    category: "deposits",
    q: "Will my deposit transaction fail if I enter zero?",
    a: "Yes. The contract enforces a ZeroAmount check and will reject any deposit of zero tokens.",
  },
  {
    id: "dep-6",
    category: "deposits",
    q: "How long does a deposit take?",
    a: "Stellar transactions typically confirm in 3–5 seconds. Your shares are available immediately after the transaction is finalized.",
  },
  {
    id: "dep-7",
    category: "deposits",
    q: "Do I need to approve the token before depositing?",
    a: "Yes, for SEP-41 tokens you must approve the vault contract to spend your tokens. The UI handles this automatically before submitting the deposit transaction.",
  },
  // Withdrawals
  {
    id: "wd-1",
    category: "withdrawals",
    q: "How do I withdraw from the vault?",
    a: "Go to the Withdraw tab, enter the number of shares you want to redeem, and confirm the transaction. The vault burns your shares and transfers the equivalent underlying tokens to your address.",
  },
  {
    id: "wd-2",
    category: "withdrawals",
    q: "How many tokens will I receive when withdrawing?",
    a: "You receive floor(shares × total_assets / total_shares) underlying tokens. Because yield accrues in total_assets over time, this amount grows relative to your original deposit.",
  },
  {
    id: "wd-3",
    category: "withdrawals",
    q: "Can I do a partial withdrawal?",
    a: "Yes. You can redeem any portion of your share balance. Your remaining shares continue to earn yield.",
  },
  {
    id: "wd-4",
    category: "withdrawals",
    q: "What happens if I try to withdraw more shares than I hold?",
    a: "The contract will reject the transaction with an InsufficientShares error (code 3). You can only redeem up to your current share balance.",
  },
  {
    id: "wd-5",
    category: "withdrawals",
    q: "Is there a withdrawal lock-up period?",
    a: "No. Withdrawals are available at any time with no lock-up or queuing period.",
  },
  {
    id: "wd-6",
    category: "withdrawals",
    q: "What if the vault doesn't have enough tokens to cover my withdrawal?",
    a: "This would trigger an InsufficientUnderlying error (code 4). In normal operation this should not occur; if it does, it may indicate a contract issue worth reporting.",
  },
  // Yield & Harvest
  {
    id: "yld-1",
    category: "yield",
    q: "How does yield work in Aura Vault?",
    a: "Yield is injected into the vault via the harvest function. A keeper calls harvest with a yield amount; those tokens are added to total_assets without minting new shares, which raises the exchange rate for all existing shareholders.",
  },
  {
    id: "yld-2",
    category: "yield",
    q: "Who can call harvest?",
    a: "Harvest is permissionless — any address can call it. This enables decentralized yield compounding without relying on a trusted operator.",
  },
  {
    id: "yld-3",
    category: "yield",
    q: "How often is yield harvested?",
    a: "Harvest frequency depends on keeper activity. Anyone can trigger a harvest at any time, so yield can be compounded as often as desired.",
  },
  {
    id: "yld-4",
    category: "yield",
    q: "Does harvesting dilute my shares?",
    a: "No. Harvest injects tokens without minting new shares, so the total share count stays the same while total_assets increases — every shareholder benefits proportionally.",
  },
  {
    id: "yld-5",
    category: "yield",
    q: "Where does the yield come from?",
    a: "Yield originates from external strategies or protocols that generate returns on the underlying token. The keeper collects those returns and injects them into the vault via harvest.",
  },
  {
    id: "yld-6",
    category: "yield",
    q: "Can I see the current APY?",
    a: "The vault itself does not store APY on-chain. The UI calculates a trailing APY estimate from historical harvest events. Actual returns vary based on harvest frequency and external strategy performance.",
  },
  // Shares & Pricing
  {
    id: "sh-1",
    category: "shares",
    q: "What determines the share price?",
    a: "Share price = total_assets / total_shares. As yield is harvested and total_assets grows, the price per share increases.",
  },
  {
    id: "sh-2",
    category: "shares",
    q: "How do I check my share balance?",
    a: "Use the balance_of(address) view function on the contract, or check the 'My Position' section in the UI.",
  },
  {
    id: "sh-3",
    category: "shares",
    q: "Why did I receive fewer shares than I deposited tokens?",
    a: "If total_assets > total_shares (i.e., the share price is above 1), you receive fewer shares than tokens deposited. Each share is worth more than one token. This is normal and expected after yield has been harvested.",
  },
  {
    id: "sh-4",
    category: "shares",
    q: "Can my share balance decrease over time?",
    a: "No. Your share balance only changes if you deposit more (balance increases) or withdraw (balance decreases). Yield accrues by increasing the value per share, not by changing your share count.",
  },
  {
    id: "sh-5",
    category: "shares",
    q: "What is the total_assets function?",
    a: "total_assets() is a read-only, gas-free view function that returns the current total of all underlying tokens held by the vault, including accrued yield.",
  },
  // Security
  {
    id: "sec-1",
    category: "security",
    q: "Has Aura Vault been audited?",
    a: "Refer to the project's official documentation and announcement channels for audit status. Always check for the latest audit reports before depositing significant funds.",
  },
  {
    id: "sec-2",
    category: "security",
    q: "What protections are in place against inflation attacks?",
    a: "The contract includes a zero-share mint rejection fence. Any deposit that would result in zero shares minted is rejected with a ZeroAmount error, preventing the classic share inflation attack.",
  },
  {
    id: "sec-3",
    category: "security",
    q: "How is arithmetic overflow prevented?",
    a: "All arithmetic uses checked_mul and checked_div operations. The Cargo.toml also sets overflow-checks = true for the release profile, so any overflow panics rather than wraps silently.",
  },
  {
    id: "sec-4",
    category: "security",
    q: "What is Checks-Effects-Interactions (CEI) ordering?",
    a: "CEI is a security pattern where all checks (validations) happen first, state changes (effects) happen second, and external calls (interactions) happen last. Aura Vault enforces CEI on every mutating function to prevent reentrancy-style attacks.",
  },
  {
    id: "sec-5",
    category: "security",
    q: "What happens to my funds if the contract storage expires on Soroban?",
    a: "The contract extends its own TTL (time-to-live) on every mutating call, targeting a 30-day lifetime with a 7-day renewal threshold. This ensures active vaults remain accessible.",
  },
  {
    id: "sec-6",
    category: "security",
    q: "Who is the admin and what can they do?",
    a: "The admin is set at initialization and can call the upgrade function to deploy a new contract Wasm. The admin cannot unilaterally withdraw user funds — withdrawals require burning shares that the user holds.",
  },
  // Technical
  {
    id: "tech-1",
    category: "technical",
    q: "What blockchain does Aura Vault run on?",
    a: "Aura Vault runs on Soroban, Stellar's smart contract platform. It is compiled to WebAssembly (Wasm) and deployed on the Stellar network.",
  },
  {
    id: "tech-2",
    category: "technical",
    q: "What is SEP-41?",
    a: "SEP-41 is the Stellar ecosystem token interface standard (analogous to ERC-20 on Ethereum). Aura Vault accepts any token that conforms to this interface.",
  },
  {
    id: "tech-3",
    category: "technical",
    q: "Can the vault be upgraded?",
    a: "Yes. The admin can upload a new Wasm binary and call the upgrade function. The contract version is incremented and an upgrade event is emitted on every successful upgrade.",
  },
  {
    id: "tech-4",
    category: "technical",
    q: "What happens to my funds during an upgrade?",
    a: "Upgrades only replace the contract code; all vault state (total_assets, share balances, admin, token address) is preserved. Your funds are not affected.",
  },
  {
    id: "tech-5",
    category: "technical",
    q: "What error codes can the contract return?",
    a: "1 NotInitialized, 2 AlreadyInitialized, 3 InsufficientShares, 4 InsufficientUnderlying, 5 ZeroAmount, 6 MathOverflow, 7 InvalidAddress, 8 ZeroShares. These are typed Soroban contract errors.",
  },
  {
    id: "tech-6",
    category: "technical",
    q: "How do I call the contract directly without the UI?",
    a: "Use the Stellar CLI: `stellar contract invoke --id <contract-id> --network mainnet -- <function> [args]`. See the README for full examples.",
  },
  {
    id: "tech-7",
    category: "technical",
    q: "Is the contract source code open source?",
    a: "Yes. The contract source is available in the aura-vault/ directory of this repository under the MIT license.",
  },
  // Fees
  {
    id: "fee-1",
    category: "fees",
    q: "Does Aura Vault charge a protocol fee?",
    a: "The current contract implementation does not enforce a protocol fee. Check the official documentation for the latest fee schedule, as this may change in future versions.",
  },
  {
    id: "fee-2",
    category: "fees",
    q: "What are the transaction costs?",
    a: "Each on-chain operation (deposit, withdraw, harvest) requires a small XLM fee to cover Soroban compute and storage costs. Fees are paid in XLM, not in the vault's underlying token.",
  },
  {
    id: "fee-3",
    category: "fees",
    q: "Are there any withdrawal fees?",
    a: "There are no withdrawal fees at the protocol level beyond the standard Stellar network transaction fee in XLM.",
  },
  {
    id: "fee-4",
    category: "fees",
    q: "Who pays the harvest transaction fee?",
    a: "The keeper who submits the harvest transaction pays the XLM network fee. This incentivizes protocol design where keepers are compensated, though the base contract does not enforce a keeper reward.",
  },
];

const es: FAQItem[] = [
  {
    id: "gs-1",
    category: "getting-started",
    q: "¿Qué es Aura Vault Protocol?",
    a: "Aura Vault Protocol es una bóveda de rendimiento basada en acciones construida en Soroban para el ecosistema Stellar. Agrega depósitos de un solo token compatible con SEP-41, emite acciones proporcionales y auto-compone el rendimiento mediante cosechas sin permiso.",
  },
  {
    id: "gs-2",
    category: "getting-started",
    q: "¿Qué necesito para usar Aura Vault?",
    a: "Necesitas una billetera compatible con Stellar, algo de XLM para las tarifas de transacción y el token subyacente aceptado por la bóveda.",
  },
  {
    id: "gs-3",
    category: "getting-started",
    q: "¿Qué redes admite Aura?",
    a: "Aura Vault está desplegado en Stellar Testnet para pruebas y Stellar Mainnet para producción. Siempre verifica el ID del contrato antes de interactuar.",
  },
  {
    id: "gs-4",
    category: "getting-started",
    q: "¿Es Aura Vault no custodial?",
    a: "Sí. Tus fondos están retenidos completamente por el contrato inteligente en cadena. Ningún miembro del equipo puede retirar tus tokens — solo tú puedes canjear tus acciones.",
  },
  {
    id: "gs-5",
    category: "getting-started",
    q: "¿Cómo conecto mi billetera?",
    a: "Haz clic en 'Conectar billetera' en el encabezado de la app y aprueba la conexión en tu extensión de billetera Stellar (por ejemplo, Freighter).",
  },
  {
    id: "gs-6",
    category: "getting-started",
    q: "¿Qué es una acción de bóveda?",
    a: "Una acción de bóveda representa tu propiedad proporcional de los activos totales. A medida que se cosecha el rendimiento, el valor de cada acción aumenta — no recibes más acciones, sino más tokens subyacentes por acción al retirar.",
  },
  {
    id: "gs-7",
    category: "getting-started",
    q: "¿Hay un depósito mínimo?",
    a: "No hay un mínimo impuesto por el protocolo más allá de requerir una cantidad distinta de cero. Sin embargo, depósitos muy pequeños pueden redondearse a cero acciones, lo que el contrato rechaza.",
  },
  {
    id: "dep-1",
    category: "deposits",
    q: "¿Cómo deposito en la bóveda?",
    a: "Ve a la pestaña de Depósito, ingresa la cantidad de tokens subyacentes que deseas depositar y confirma la transacción en tu billetera. Las acciones se acuñan y se acreditan a tu dirección de inmediato.",
  },
  {
    id: "dep-2",
    category: "deposits",
    q: "¿Cómo se calculan mis acciones al depositar?",
    a: "El primer depositante recibe acciones 1:1 con su depósito. Los siguientes reciben floor(cantidad × total_acciones / total_activos) acciones, asegurando una propiedad proporcional justa.",
  },
  {
    id: "dep-3",
    category: "deposits",
    q: "¿Puedo depositar varias veces?",
    a: "Sí. Cada depósito acuña acciones adicionales al tipo de cambio actual. Tu saldo total de acciones se acumula en todos los depósitos.",
  },
  {
    id: "dep-4",
    category: "deposits",
    q: "¿Qué token acepta la bóveda?",
    a: "Cada bóveda acepta exactamente un token subyacente compatible con SEP-41, establecido en la inicialización. Verifica la página de detalles de la bóveda.",
  },
  {
    id: "dep-5",
    category: "deposits",
    q: "¿Fallará mi transacción si ingreso cero?",
    a: "Sí. El contrato aplica una verificación de ZeroAmount y rechazará cualquier depósito de cero tokens.",
  },
  {
    id: "dep-6",
    category: "deposits",
    q: "¿Cuánto tarda un depósito?",
    a: "Las transacciones de Stellar generalmente se confirman en 3–5 segundos. Tus acciones están disponibles inmediatamente después de que se finaliza la transacción.",
  },
  {
    id: "dep-7",
    category: "deposits",
    q: "¿Necesito aprobar el token antes de depositar?",
    a: "Sí, para tokens SEP-41 debes aprobar que el contrato de la bóveda gaste tus tokens. La interfaz maneja esto automáticamente antes de enviar la transacción.",
  },
  { id: "wd-1", category: "withdrawals", q: "¿Cómo retiro de la bóveda?", a: "Ve a la pestaña de Retiro, ingresa el número de acciones a canjear y confirma la transacción. La bóveda quema tus acciones y transfiere los tokens subyacentes equivalentes a tu dirección." },
  { id: "wd-2", category: "withdrawals", q: "¿Cuántos tokens recibiré al retirar?", a: "Recibes floor(acciones × total_activos / total_acciones) tokens subyacentes. Como el rendimiento se acumula en total_activos con el tiempo, esta cantidad crece respecto a tu depósito original." },
  { id: "wd-3", category: "withdrawals", q: "¿Puedo hacer un retiro parcial?", a: "Sí. Puedes canjear cualquier porción de tu saldo de acciones. Las acciones restantes siguen generando rendimiento." },
  { id: "wd-4", category: "withdrawals", q: "¿Qué pasa si intento retirar más acciones de las que tengo?", a: "El contrato rechazará la transacción con un error InsufficientShares (código 3)." },
  { id: "wd-5", category: "withdrawals", q: "¿Hay un período de bloqueo de retiro?", a: "No. Los retiros están disponibles en cualquier momento sin período de bloqueo." },
  { id: "wd-6", category: "withdrawals", q: "¿Qué pasa si la bóveda no tiene suficientes tokens?", a: "Esto activaría un error InsufficientUnderlying (código 4). En operación normal esto no debería ocurrir." },
  { id: "yld-1", category: "yield", q: "¿Cómo funciona el rendimiento en Aura Vault?", a: "El rendimiento se inyecta mediante la función harvest. Un guardián llama a harvest con una cantidad de rendimiento; esos tokens se agregan a total_activos sin acuñar nuevas acciones, elevando el tipo de cambio para todos." },
  { id: "yld-2", category: "yield", q: "¿Quién puede llamar a harvest?", a: "Harvest es sin permiso — cualquier dirección puede llamarla." },
  { id: "yld-3", category: "yield", q: "¿Con qué frecuencia se cosecha el rendimiento?", a: "La frecuencia depende de la actividad del guardián. Cualquiera puede activar una cosecha en cualquier momento." },
  { id: "yld-4", category: "yield", q: "¿La cosecha diluye mis acciones?", a: "No. Harvest inyecta tokens sin acuñar nuevas acciones, por lo que todos los accionistas se benefician proporcionalmente." },
  { id: "yld-5", category: "yield", q: "¿De dónde proviene el rendimiento?", a: "El rendimiento proviene de estrategias o protocolos externos que generan retornos sobre el token subyacente." },
  { id: "yld-6", category: "yield", q: "¿Puedo ver el APY actual?", a: "La bóveda no almacena APY en cadena. La interfaz calcula una estimación de APY a partir de eventos históricos de cosecha." },
  { id: "sh-1", category: "shares", q: "¿Qué determina el precio de las acciones?", a: "Precio = total_activos / total_acciones. A medida que crece total_activos con el rendimiento cosechado, el precio por acción aumenta." },
  { id: "sh-2", category: "shares", q: "¿Cómo verifico mi saldo de acciones?", a: "Usa la función de vista balance_of(dirección) en el contrato o revisa la sección 'Mi Posición' en la interfaz." },
  { id: "sh-3", category: "shares", q: "¿Por qué recibí menos acciones que tokens deposité?", a: "Si total_activos > total_acciones, recibes menos acciones que tokens depositados. Cada acción vale más de un token. Esto es normal tras cosechar rendimiento." },
  { id: "sh-4", category: "shares", q: "¿Puede disminuir mi saldo de acciones con el tiempo?", a: "No. Tu saldo de acciones solo cambia si depositas más o retiras. El rendimiento se acumula aumentando el valor por acción." },
  { id: "sh-5", category: "shares", q: "¿Qué es la función total_assets?", a: "total_assets() es una función de vista de solo lectura que devuelve el total actual de todos los tokens subyacentes en la bóveda, incluido el rendimiento acumulado." },
  { id: "sec-1", category: "security", q: "¿Ha sido auditado Aura Vault?", a: "Consulta la documentación oficial y los canales de anuncios del proyecto para conocer el estado de la auditoría." },
  { id: "sec-2", category: "security", q: "¿Qué protecciones existen contra ataques de inflación?", a: "El contrato incluye una valla de rechazo de acuñación de cero acciones, previniendo el ataque clásico de inflación de acciones." },
  { id: "sec-3", category: "security", q: "¿Cómo se previene el desbordamiento aritmético?", a: "Toda la aritmética usa operaciones checked_mul y checked_div. El perfil de lanzamiento también establece overflow-checks = true." },
  { id: "sec-4", category: "security", q: "¿Qué es el ordenamiento Checks-Effects-Interactions (CEI)?", a: "CEI es un patrón de seguridad donde todas las validaciones ocurren primero, los cambios de estado segundo y las llamadas externas al final. Aura Vault aplica CEI en cada función mutante." },
  { id: "sec-5", category: "security", q: "¿Qué pasa si el almacenamiento del contrato expira en Soroban?", a: "El contrato extiende su propio TTL en cada llamada mutante, con un objetivo de 30 días y un umbral de renovación de 7 días." },
  { id: "sec-6", category: "security", q: "¿Quién es el administrador y qué puede hacer?", a: "El administrador puede llamar a la función upgrade para desplegar un nuevo Wasm. No puede retirar fondos de usuarios unilateralmente." },
  { id: "tech-1", category: "technical", q: "¿En qué blockchain funciona Aura Vault?", a: "Aura Vault funciona en Soroban, la plataforma de contratos inteligentes de Stellar, compilado a WebAssembly." },
  { id: "tech-2", category: "technical", q: "¿Qué es SEP-41?", a: "SEP-41 es el estándar de interfaz de token del ecosistema Stellar, análogo a ERC-20 en Ethereum." },
  { id: "tech-3", category: "technical", q: "¿Puede actualizarse la bóveda?", a: "Sí. El administrador puede subir un nuevo binario Wasm y llamar a la función upgrade." },
  { id: "tech-4", category: "technical", q: "¿Qué pasa con mis fondos durante una actualización?", a: "Las actualizaciones solo reemplazan el código del contrato; todo el estado de la bóveda se conserva." },
  { id: "tech-5", category: "technical", q: "¿Qué códigos de error puede devolver el contrato?", a: "1 NotInitialized, 2 AlreadyInitialized, 3 InsufficientShares, 4 InsufficientUnderlying, 5 ZeroAmount, 6 MathOverflow, 7 InvalidAddress, 8 ZeroShares." },
  { id: "tech-6", category: "technical", q: "¿Cómo llamo al contrato directamente sin la interfaz?", a: "Usa el CLI de Stellar: `stellar contract invoke --id <contract-id> --network mainnet -- <función> [args]`." },
  { id: "tech-7", category: "technical", q: "¿El código fuente del contrato es de código abierto?", a: "Sí. El código fuente está disponible en el directorio aura-vault/ de este repositorio bajo la licencia MIT." },
  { id: "fee-1", category: "fees", q: "¿Cobra Aura Vault una tarifa de protocolo?", a: "La implementación actual no aplica una tarifa de protocolo. Consulta la documentación oficial para el último calendario de tarifas." },
  { id: "fee-2", category: "fees", q: "¿Cuáles son los costos de transacción?", a: "Cada operación en cadena requiere una pequeña tarifa de XLM para cubrir los costos de cómputo y almacenamiento de Soroban." },
  { id: "fee-3", category: "fees", q: "¿Hay tarifas de retiro?", a: "No hay tarifas de retiro a nivel de protocolo más allá de la tarifa de red estándar de Stellar en XLM." },
  { id: "fee-4", category: "fees", q: "¿Quién paga la tarifa de transacción de harvest?", a: "El guardián que envía la transacción de harvest paga la tarifa de red en XLM." },
];

const fr: FAQItem[] = [
  {
    id: "gs-1",
    category: "getting-started",
    q: "Qu'est-ce qu'Aura Vault Protocol ?",
    a: "Aura Vault Protocol est un coffre de rendement basé sur des parts, construit sur Soroban pour l'écosystème Stellar. Il agrège les dépôts d'un seul jeton compatible SEP-41, émet des parts proportionnelles et auto-compose le rendement via des récoltes sans permission.",
  },
  {
    id: "gs-2",
    category: "getting-started",
    q: "De quoi ai-je besoin pour utiliser Aura Vault ?",
    a: "Vous avez besoin d'un portefeuille compatible Stellar, de XLM pour les frais de transaction et du jeton sous-jacent accepté par le coffre.",
  },
  {
    id: "gs-3",
    category: "getting-started",
    q: "Quels réseaux Aura prend-il en charge ?",
    a: "Aura Vault est déployé sur Stellar Testnet pour les tests et Stellar Mainnet pour la production. Vérifiez toujours l'ID du contrat avant d'interagir.",
  },
  {
    id: "gs-4",
    category: "getting-started",
    q: "Aura Vault est-il non-custodial ?",
    a: "Oui. Vos fonds sont détenus entièrement par le contrat intelligent on-chain. Aucun membre de l'équipe ne peut retirer vos jetons — seul vous pouvez racheter vos parts.",
  },
  {
    id: "gs-5",
    category: "getting-started",
    q: "Comment connecter mon portefeuille ?",
    a: "Cliquez sur 'Connecter le portefeuille' dans l'en-tête de l'application et approuvez la connexion dans votre extension de portefeuille Stellar (ex. Freighter).",
  },
  {
    id: "gs-6",
    category: "getting-started",
    q: "Qu'est-ce qu'une part de coffre ?",
    a: "Une part représente votre propriété proportionnelle des actifs totaux du coffre. À mesure que le rendement est récolté, la valeur de chaque part augmente — vous ne recevez pas plus de parts, mais plus de jetons sous-jacents par part au moment du retrait.",
  },
  {
    id: "gs-7",
    category: "getting-started",
    q: "Y a-t-il un dépôt minimum ?",
    a: "Il n'y a pas de minimum imposé par le protocole au-delà d'un montant non nul. Cependant, de très petits dépôts peuvent être arrondis à zéro parts, ce que le contrat rejette.",
  },
  {
    id: "dep-1",
    category: "deposits",
    q: "Comment déposer dans le coffre ?",
    a: "Accédez à l'onglet Dépôt, saisissez le montant de jetons sous-jacents à déposer et confirmez la transaction dans votre portefeuille. Les parts sont frappées et créditées instantanément.",
  },
  {
    id: "dep-2",
    category: "deposits",
    q: "Comment mes parts sont-elles calculées lors d'un dépôt ?",
    a: "Le premier déposant reçoit des parts 1:1 avec son dépôt. Les suivants reçoivent floor(montant × total_parts / total_actifs) parts, assurant une propriété proportionnelle équitable.",
  },
  {
    id: "dep-3",
    category: "deposits",
    q: "Puis-je déposer plusieurs fois ?",
    a: "Oui. Chaque dépôt frappe des parts supplémentaires au taux de change actuel. Votre solde total de parts s'accumule sur tous les dépôts.",
  },
  {
    id: "dep-4",
    category: "deposits",
    q: "Quel jeton le coffre accepte-t-il ?",
    a: "Chaque coffre accepte exactement un jeton sous-jacent compatible SEP-41, défini à l'initialisation. Vérifiez la page de détails du coffre pour confirmer.",
  },
  {
    id: "dep-5",
    category: "deposits",
    q: "Ma transaction échouera-t-elle si je saisie zéro ?",
    a: "Oui. Le contrat applique une vérification ZeroAmount et rejettera tout dépôt de zéro jeton.",
  },
  {
    id: "dep-6",
    category: "deposits",
    q: "Combien de temps dure un dépôt ?",
    a: "Les transactions Stellar se confirment généralement en 3 à 5 secondes. Vos parts sont disponibles immédiatement après la finalisation.",
  },
  {
    id: "dep-7",
    category: "deposits",
    q: "Dois-je approuver le jeton avant de déposer ?",
    a: "Oui, pour les jetons SEP-41 vous devez autoriser le contrat du coffre à dépenser vos jetons. L'interface gère cela automatiquement.",
  },
  { id: "wd-1", category: "withdrawals", q: "Comment retirer du coffre ?", a: "Accédez à l'onglet Retrait, saisissez le nombre de parts à racheter et confirmez la transaction. Le coffre brûle vos parts et transfère les jetons équivalents à votre adresse." },
  { id: "wd-2", category: "withdrawals", q: "Combien de jetons recevrai-je lors d'un retrait ?", a: "Vous recevez floor(parts × total_actifs / total_parts) jetons sous-jacents. Ce montant augmente avec le temps grâce au rendement accumulé." },
  { id: "wd-3", category: "withdrawals", q: "Puis-je effectuer un retrait partiel ?", a: "Oui. Vous pouvez racheter n'importe quelle portion de votre solde de parts. Les parts restantes continuent de générer du rendement." },
  { id: "wd-4", category: "withdrawals", q: "Que se passe-t-il si je tente de retirer plus de parts que je n'en possède ?", a: "Le contrat rejettera la transaction avec une erreur InsufficientShares (code 3)." },
  { id: "wd-5", category: "withdrawals", q: "Y a-t-il une période de blocage des retraits ?", a: "Non. Les retraits sont disponibles à tout moment sans période de blocage." },
  { id: "wd-6", category: "withdrawals", q: "Que se passe-t-il si le coffre n'a pas assez de jetons ?", a: "Cela déclencherait une erreur InsufficientUnderlying (code 4). En fonctionnement normal, cela ne devrait pas se produire." },
  { id: "yld-1", category: "yield", q: "Comment fonctionne le rendement dans Aura Vault ?", a: "Le rendement est injecté via la fonction harvest. Un gardien appelle harvest avec un montant de rendement ; ces jetons sont ajoutés aux total_actifs sans frapper de nouvelles parts." },
  { id: "yld-2", category: "yield", q: "Qui peut appeler harvest ?", a: "Harvest est sans permission — n'importe quelle adresse peut l'appeler." },
  { id: "yld-3", category: "yield", q: "À quelle fréquence le rendement est-il récolté ?", a: "La fréquence dépend de l'activité des gardiens. N'importe qui peut déclencher une récolte à tout moment." },
  { id: "yld-4", category: "yield", q: "La récolte dilue-t-elle mes parts ?", a: "Non. Harvest injecte des jetons sans frapper de nouvelles parts, donc tous les actionnaires en bénéficient proportionnellement." },
  { id: "yld-5", category: "yield", q: "D'où vient le rendement ?", a: "Le rendement provient de stratégies ou protocoles externes qui génèrent des retours sur le jeton sous-jacent." },
  { id: "yld-6", category: "yield", q: "Puis-je voir l'APY actuel ?", a: "Le coffre ne stocke pas l'APY on-chain. L'interface calcule une estimation d'APY à partir des événements de récolte historiques." },
  { id: "sh-1", category: "shares", q: "Qu'est-ce qui détermine le prix d'une part ?", a: "Prix = total_actifs / total_parts. À mesure que total_actifs augmente avec le rendement récolté, le prix par part augmente." },
  { id: "sh-2", category: "shares", q: "Comment vérifier mon solde de parts ?", a: "Utilisez la fonction de vue balance_of(adresse) sur le contrat ou consultez la section 'Ma Position' dans l'interface." },
  { id: "sh-3", category: "shares", q: "Pourquoi ai-je reçu moins de parts que de jetons déposés ?", a: "Si total_actifs > total_parts, vous recevez moins de parts que de jetons déposés. Chaque part vaut plus d'un jeton. C'est normal après récolte de rendement." },
  { id: "sh-4", category: "shares", q: "Mon solde de parts peut-il diminuer avec le temps ?", a: "Non. Votre solde de parts ne change que si vous déposez plus ou retirez. Le rendement s'accumule en augmentant la valeur par part." },
  { id: "sh-5", category: "shares", q: "Qu'est-ce que la fonction total_assets ?", a: "total_assets() est une fonction de vue en lecture seule qui retourne le total actuel de tous les jetons sous-jacents dans le coffre, y compris le rendement accumulé." },
  { id: "sec-1", category: "security", q: "Aura Vault a-t-il été audité ?", a: "Consultez la documentation officielle et les canaux d'annonces du projet pour connaître le statut d'audit." },
  { id: "sec-2", category: "security", q: "Quelles protections existent contre les attaques d'inflation ?", a: "Le contrat inclut une barrière de rejet de frappe de zéro parts, empêchant l'attaque classique d'inflation de parts." },
  { id: "sec-3", category: "security", q: "Comment le dépassement arithmétique est-il évité ?", a: "Toute l'arithmétique utilise des opérations checked_mul et checked_div. Le profil de version inclut également overflow-checks = true." },
  { id: "sec-4", category: "security", q: "Qu'est-ce que l'ordonnancement Checks-Effects-Interactions (CEI) ?", a: "CEI est un modèle de sécurité où toutes les validations ont lieu en premier, les changements d'état en second et les appels externes en dernier. Aura Vault applique CEI sur chaque fonction mutante." },
  { id: "sec-5", category: "security", q: "Que se passe-t-il si le stockage du contrat expire sur Soroban ?", a: "Le contrat étend son propre TTL à chaque appel mutant, ciblant une durée de vie de 30 jours avec un seuil de renouvellement de 7 jours." },
  { id: "sec-6", category: "security", q: "Qui est l'administrateur et que peut-il faire ?", a: "L'administrateur peut appeler la fonction upgrade pour déployer un nouveau Wasm. Il ne peut pas retirer unilatéralement les fonds des utilisateurs." },
  { id: "tech-1", category: "technical", q: "Sur quelle blockchain Aura Vault fonctionne-t-il ?", a: "Aura Vault fonctionne sur Soroban, la plateforme de contrats intelligents de Stellar, compilé en WebAssembly." },
  { id: "tech-2", category: "technical", q: "Qu'est-ce que SEP-41 ?", a: "SEP-41 est la norme d'interface de jeton de l'écosystème Stellar, analogue à ERC-20 sur Ethereum." },
  { id: "tech-3", category: "technical", q: "Le coffre peut-il être mis à jour ?", a: "Oui. L'administrateur peut télécharger un nouveau binaire Wasm et appeler la fonction upgrade." },
  { id: "tech-4", category: "technical", q: "Que se passe-t-il avec mes fonds lors d'une mise à jour ?", a: "Les mises à jour ne remplacent que le code du contrat ; tout l'état du coffre est préservé." },
  { id: "tech-5", category: "technical", q: "Quels codes d'erreur le contrat peut-il retourner ?", a: "1 NotInitialized, 2 AlreadyInitialized, 3 InsufficientShares, 4 InsufficientUnderlying, 5 ZeroAmount, 6 MathOverflow, 7 InvalidAddress, 8 ZeroShares." },
  { id: "tech-6", category: "technical", q: "Comment appeler le contrat directement sans l'interface ?", a: "Utilisez le CLI Stellar : `stellar contract invoke --id <contract-id> --network mainnet -- <fonction> [args]`." },
  { id: "tech-7", category: "technical", q: "Le code source du contrat est-il open source ?", a: "Oui. Le code source est disponible dans le répertoire aura-vault/ de ce dépôt sous licence MIT." },
  { id: "fee-1", category: "fees", q: "Aura Vault facture-t-il des frais de protocole ?", a: "L'implémentation actuelle n'applique pas de frais de protocole. Consultez la documentation officielle pour le dernier calendrier de frais." },
  { id: "fee-2", category: "fees", q: "Quels sont les coûts de transaction ?", a: "Chaque opération on-chain nécessite de petits frais XLM pour couvrir les coûts de calcul et de stockage Soroban." },
  { id: "fee-3", category: "fees", q: "Y a-t-il des frais de retrait ?", a: "Il n'y a pas de frais de retrait au niveau du protocole au-delà des frais de réseau Stellar standard en XLM." },
  { id: "fee-4", category: "fees", q: "Qui paie les frais de transaction harvest ?", a: "Le gardien qui soumet la transaction harvest paie les frais de réseau en XLM." },
];

export const faqData: Record<Locale, FAQItem[]> = { en, es, fr };
